### ISSUE TITLE
代码复现第4步（训练）遇到问题

### ISSUE THREAD

**Issue by liangbingtao** [yumath/bertNER#23]
博主你好，我在复现您的代码的时候，进行到训练过程这一步（第4步），控制台输出如下错误，请问能帮助解答一下这是我哪里没有注意到吗，应该如何解决呢？
```
D:\developer_tools\Anaconda\envs\bertNER\python.exe E:/开题/NER_code/bertNER/train.py
Found 9 unique named entity tags
20864 / 0 / 4636 sentences in train / dev / test.
2021-02-15 13:03:09,605 - log\train.log - INFO - num_tags       :	9
2021-02-15 13:03:09,605 - log\train.log - INFO - lstm_dim       :	200
2021-02-15 13:03:09,606 - log\train.log - INFO - batch_size     :	128
2021-02-15 13:03:09,606 - log\train.log - INFO - max_seq_len    :	128
2021-02-15 13:03:09,606 - log\train.log - INFO - clip           :	5
2021-02-15 13:03:09,606 - log\train.log - INFO - dropout_keep   :	0.5
2021-02-15 13:03:09,606 - log\train.log - INFO - optimizer      :	adam
2021-02-15 13:03:09,606 - log\train.log - INFO - lr             :	0.001
2021-02-15 13:03:09,606 - log\train.log - INFO - tag_schema     :	iob
2021-02-15 13:03:09,606 - log\train.log - INFO - zeros          :	False
2021-02-15 13:03:09,606 - log\train.log - INFO - lower          :	True
2021-02-15 13:03:09.607092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.607092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.607092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.608092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.608092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.608092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.609092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2021-02-15 13:03:09.610092: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "E:/开题/NER_code/bertNER/train.py", line 179, in <module>
    tf.app.run(main)
  File "D:\developer_tools\Anaconda\envs\bertNER\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:/开题/NER_code/bertNER/train.py", line 175, in main
    train()
  File "E:/开题/NER_code/bertNER/train.py", line 150, in train
    model = create_model(sess, Model, FLAGS.ckpt_path, config, logger)
  File "E:\开题\NER_code\bertNER\utils.py", line 177, in create_model
    model = Model_class(config)
  File "E:\开题\NER_code\bertNER\model.py", line 40, in __init__
    embedding = self.bert_embedding()
  File "E:\开题\NER_code\bertNER\model.py", line 101, in bert_embedding
    use_one_hot_embeddings=False)
  File "E:\开题\NER_code\bertNER\bert\modeling.py", line 194, in __init__
    dropout_prob=config.hidden_dropout_prob)
  File "E:\开题\NER_code\bertNER\bert\modeling.py", line 520, in embedding_postprocessor
    output = layer_norm_and_dropout(output, dropout_prob)
  File "E:\开题\NER_code\bertNER\bert\modeling.py", line 370, in layer_norm_and_dropout
    output_tensor = layer_norm(input_tensor, name)
  File "E:\开题\NER_code\bertNER\bert\modeling.py", line 365, in layer_norm
    inputs=input_tensor, begin_norm_axis=-1, begin_params_axis=-1, scope=name)
  File "D:\developer_tools\Anaconda\envs\bertNER\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
TypeError: layer_norm() got an unexpected keyword argument 'begin_norm_axis'
Process finished with exit code 1
```

**Comment by yumath** [comment]
@BingtaoLiang 看你好像用的conda环境，请先确定环境配置与操作步骤一致。

**Comment by BingtaoLiang** [comment]
> @BingtaoLiang 看你好像用的conda环境，请先确定环境配置与操作步骤一致。

好的，感谢回复，这个没有GPU能跑吗，打算在我的2核4G的服务器上训练，不知道要训练多久

**Comment by liangbingtao** [comment]
> @BingtaoLiang 看你好像用的conda环境，请先确定环境配置与操作步骤一致。

好的，感谢回复，我再试一下

**Comment by liangbingtao** [comment]
> @BingtaoLiang 看你好像用的conda环境，请先确定环境配置与操作步骤一致。

你好，请问这个算是训练完成了吗，精度没有达到预期的效果呢，是不是还要改哪些参数，下面是我的日志，麻烦您再帮我解惑，感谢！！

`2021-02-22 00:59:21,511 - log\train.log - INFO - num_tags       :	9
2021-02-22 00:59:21,521 - log\train.log - INFO - lstm_dim       :	200
2021-02-22 00:59:21,521 - log\train.log - INFO - batch_size     :	128
2021-02-22 00:59:21,521 - log\train.log - INFO - max_seq_len    :	128
2021-02-22 00:59:21,521 - log\train.log - INFO - clip           :	5.0
2021-02-22 00:59:21,521 - log\train.log - INFO - dropout_keep   :	0.5
2021-02-22 00:59:21,521 - log\train.log - INFO - optimizer      :	adam
2021-02-22 00:59:21,521 - log\train.log - INFO - lr             :	0.001
2021-02-22 00:59:21,521 - log\train.log - INFO - tag_schema     :	iob
2021-02-22 00:59:21,521 - log\train.log - INFO - zeros          :	False
2021-02-22 00:59:21,521 - log\train.log - INFO - lower          :	True
2021-02-22 00:59:29,081 - log\train.log - INFO - Created model with fresh parameters.
2021-02-22 00:59:30,261 - log\train.log - INFO - start training
2021-02-22 03:56:54,944 - log\train.log - INFO - iteration:1 step:100/163, NER loss: 8.407235
2021-02-22 05:47:21,221 - log\train.log - INFO - **evaluate:dev**
2021-02-22 06:18:44,810 - log\train.log - INFO - processed 106932 tokens with 3661 phrases; found: 3697 phrases; correct: 3092.

2021-02-22 06:18:44,810 - log\train.log - INFO - accuracy:  98.58%; precision:  83.64%; recall:  84.46%; FB1:  84.04

2021-02-22 06:18:44,810 - log\train.log - INFO -                  : precision:   0.00%; recall:   0.00%; FB1:   0.00  3

2021-02-22 06:18:44,810 - log\train.log - INFO -               LOC: precision:  83.94%; recall:  84.55%; FB1:  84.24  1812

2021-02-22 06:18:44,810 - log\train.log - INFO -               ORG: precision:  74.55%; recall:  75.61%; FB1:  75.08  990

2021-02-22 06:18:44,810 - log\train.log - INFO -               PER: precision:  93.39%; recall:  94.44%; FB1:  93.91  892

2021-02-22 06:18:44,978 - log\train.log - INFO - **new best dev f1 score:84.040**
2021-02-22 06:18:56,372 - log\train.log - INFO - model saved
2021-02-22 06:18:56,372 - log\train.log - INFO - **evaluate:test**
2021-02-22 07:21:41,547 - log\train.log - INFO - processed 214621 tokens with 7456 phrases; found: 7619 phrases; correct: 6261.

2021-02-22 07:21:41,547 - log\train.log - INFO - accuracy:  98.43%; precision:  82.18%; recall:  83.97%; FB1:  83.06

2021-02-22 07:21:41,547 - log\train.log - INFO -                  : precision:   0.00%; recall:   0.00%; FB1:   0.00  3

2021-02-22 07:21:41,547 - log\train.log - INFO -               LOC: precision:  82.66%; recall:  84.35%; FB1:  83.50  3535

2021-02-22 07:21:41,547 - log\train.log - INFO -               ORG: precision:  73.30%; recall:  76.04%; FB1:  74.64  2247

2021-02-22 07:21:41,547 - log\train.log - INFO -               PER: precision:  92.26%; recall:  92.97%; FB1:  92.61  1834

2021-02-22 07:21:41,737 - log\train.log - INFO - **new best test f1 score:83.060**
2021-02-22 08:26:20,947 - log\train.log - INFO - iteration:2 step:37/163, NER loss: 2.939173
`
